<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VersionPrefix>0.0.1</VersionPrefix>
    <VersionSuffix>preview-02</VersionSuffix>
    <RootNamespace>TypeSafeAI.Sdk</RootNamespace>
    <Authors>Stef Heyenrath</Authors>
    <Company>TypeSafe-AI.Sdk</Company>
    <Product>TypeSafe-AI.Sdk</Product>
    <Copyright>Copyright (c) 2026 Stef Heyenrath</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/StefH/typesafe-ai.sdk</PackageProjectUrl>
    <RepositoryUrl>https://github.com/StefH/typesafe-ai.sdk</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>ai;typesafe;jev;sdk;c#</PackageTags>
    <Description>TypeSafe-AI .NET SDK</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsPackable)' != 'false'">
    <None Include="README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

  <PropertyGroup>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <!--<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>-->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    <PackageReference Include="ZeroAlloc.Rest" />
    <PackageReference Include="ZeroAlloc.Rest.SystemTextJson" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

</Project>